[tool.poetry]
name = "handydandy"
version = "0.1.0"
description = ""
authors = ["lucasammer <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
twine = "^3.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
